name: function-tests
on:
  push:
  workflow_dispatch:
 
jobs:
  function_tests:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@v3

    - name: 'Install'
      run: |
        npm install

    - name: 'Test azure cli'
      uses: ./
      with:
        azcliversion: 2.30.0
        inlineScript: |
          ls -la ~
          az -v